SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME ,EMPLOYEES.DEPARTMENT_ID
FROM EMPLOYEES,DEPARTMENTS
WHERE EMPLOYEES.DEPARTMENT_ID=DEPARTMENTS.DEPARTMENT_ID;

--   JOIN QUEARY  
SELECT EMPLOYEES.FIRST_NAME,DEPARTMENTS.DEPARTMENT_NAME
FROM EMPLOYEES JOIN DEPARTMENTS ;

   --  LEFT JOIN ---
select DEPARTMENTS.DEPARTMENT_NAME
FROM DEPARTMENTS
	LEFT JOIN EMPLOYEES 
		ON DEPARTMENTS.DEPARTMENT_ID=EMPLOYEES.DEPARTMENT_ID
	WHERE EMPLOYEES.DEPARTMENT_ID IS NULL;
 